//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pronto.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pronto.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @InsertedRows AS TABLE (Id int);
        ///
        ///INSERT INTO [Pronto].[Route]
        ///           ([RouteDate]
        ///           ,[DriverID]
        ///           ,[TruckId]
        ///           ,[DepatureTime]
        ///           ,[ArrivelTime]
        ///           ,[DepartureMilage]
        ///           ,[ArrivelMilage]
        ///           ,[TotolCod]
        ///           ,[CodDecrepency]
        ///           ,[HotelInfo]
        ///           ,[HotelReceipt]
        ///           ,[BreakAStart]
        ///           ,[BreakAEnd]
        ///           ,[BreakBStart]
        ///           ,[BreakBEnd]
        ///           ,[LunchStart]
        ///           ,[Lu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsertRoute {
            get {
                return ResourceManager.GetString("InsertRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [Pronto].[Stop]
        ///           ([CustomerId]
        ///           ,[ServiceId]
        ///           ,[RouteId]
        ///           ,[PtsId]
        ///           ,[ClientName]
        ///           ,[ClientAddr]
        ///		   ,[ClientCity]
        ///		   ,[ClientZipCode]
        ///		   ,[ClientState]
        ///           ,[ClientPh]
        ///           ,[QbDocNo]
        ///           ,[PadId]
        ///           ,[PhoneId]
        ///           ,[Eta]
        ///           ,[StopCodAmount]
        ///           ,[StopArrivalTime]
        ///           ,[StopDepartTime]
        ///           ,[StopMlgMeterRead]
        ///		   ,[StopNote])
        ///     VALUES
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsertStop {
            get {
                return ResourceManager.GetString("InsertStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;WITH DETAILS AS
        ///(
        ///
        ///SELECT R.RootNo As RouteNo
        ///,R.RouteDate
        ///,D.DriverName
        ///,T.TruckId
        ///,R.DepatureTime
        ///,R.ArrivelTime
        ///,R.DepartureMilage
        ///,R.ArrivelMilage
        ///,R.RouteMlg
        ///,R.[TotolCod]
        ///,R.[CodDecrepency]
        ///,R.[HotelInfo]
        ///,R.[HotelReceipt]
        ///,R.[BreakAStart]
        ///,R.[BreakAEnd]
        ///,R.[BreakBStart]
        ///,R.[BreakBEnd]
        ///,R.[LunchStart]
        ///,R.[LunchEnd]
        ///,R.[DinnerStart]
        ///,R.[DinnerEnd]
        ///,R.DriverComments
        ///,[Pronto].[GetHelpers](R.RootNo) AS HELPERS
        ///,[Pronto].[GetCustomer](R.RootNo) AS Customers
        ///,[Pronto].[GetServic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;WITH DETAILS AS
        ///(
        ///
        ///SELECT R.RootNo As RouteNo
        ///,R.RouteDate
        ///,D.DriverName
        ///,T.TruckId
        ///,R.DepatureTime
        ///,R.ArrivelTime
        ///,R.DepartureMilage
        ///,R.ArrivelMilage
        ///,R.RouteMlg
        ///,R.[TotolCod]
        ///,R.[CodDecrepency]
        ///,R.[HotelInfo]
        ///,R.[HotelReceipt]
        ///,R.[BreakAStart]
        ///,R.[BreakAEnd]
        ///,R.[BreakBStart]
        ///,R.[BreakBEnd]
        ///,R.[LunchStart]
        ///,R.[LunchEnd]
        ///,R.[DinnerStart]
        ///,R.[DinnerEnd]
        ///,R.DriverComments
        ///,[Pronto].[GetHelpers](R.RootNo) AS HELPERS
        ///,[Pronto].[GetCustomer](R.RootNo) AS Customers
        ///,[Pronto].[GetServic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchByRoot {
            get {
                return ResourceManager.GetString("SearchByRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///
        ///D.ID
        ///,D.DriverName
        ///,T.ID
        ///,T.TruckId
        ///FROM Pronto.Route R
        ///JOIN Pronto.Drivers D ON D.ID = R.DriverID
        ///JOIN Pronto.Truck T ON T.ID = R.TruckId
        ///
        ///WHERE R.RootNo ={0}.
        /// </summary>
        internal static string SelectDriver {
            get {
                return ResourceManager.GetString("SelectDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///
        ///
        ///HL.ID,HL.HelperName
        ///FROM Pronto.Route R
        ///JOIN Pronto.Drivers D ON D.ID = R.DriverID
        ///JOIN Pronto.Truck T ON T.ID = R.TruckId
        ///JOIN Pronto.RouteHelpers H ON R.RootNo = H.RouteId
        ///JOIN Pronto.Helper HL ON HL.ID = H.HelperId
        ///
        ///WHERE R.RootNo ={0}.
        /// </summary>
        internal static string SelectHelpers {
            get {
                return ResourceManager.GetString("SelectHelpers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT R.RootNo
        ///,R.RouteDate
        ///,R.DepatureTime
        ///,R.ArrivelTime
        ///,R.DepartureMilage
        ///,R.ArrivelMilage
        ///,R.DepartureMilage
        ///,R.ArrivelMilage
        ///,R.RouteMlg
        ///,R.TotolCod
        ///,R.CodDecrepency
        ///,R.HotelInfo
        ///,R.HotelReceipt
        ///,R.BreakAStart
        ///,R.BreakAEnd
        ///,R.BreakBStart
        ///,R.BreakBEnd
        ///,R.LunchStart
        ///,R.LunchEnd
        ///,R.DinnerStart
        ///,R.DinnerEnd
        ///,R.DriverComments
        ///,D.ID
        ///,D.DriverName
        ///,T.ID
        ///,T.TruckId
        ///FROM Pronto.Route R
        ///JOIN Pronto.Drivers D ON D.ID = R.DriverID
        ///JOIN Pronto.Truck T ON T.ID = R.TruckId
        ///
        ///WHERE R.Roo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectRoot {
            get {
                return ResourceManager.GetString("SelectRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///C.ID
        ///,C.CustomerName
        ///
        ///FROM Pronto.Stop S
        ///JOIN PRONTO.Customer C ON S.CustomerId = C.ID
        ///JOIN Pronto.Service SV ON SV.ID = S.ServiceId
        ///WHERE S.ID = {0}.
        /// </summary>
        internal static string SelectSingleStopCustomer {
            get {
                return ResourceManager.GetString("SelectSingleStopCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///SV.ID
        ///,SV.ServiceType
        ///
        ///FROM Pronto.Stop S
        ///JOIN PRONTO.Customer C ON S.CustomerId = C.ID
        ///JOIN Pronto.Service SV ON SV.ID = S.ServiceId
        ///WHERE S.ID = {0}.
        /// </summary>
        internal static string SelectSingleStopService {
            get {
                return ResourceManager.GetString("SelectSingleStopService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT S.ID
        ///,S.PtsId
        ///,S.ClientName
        ///,S.ClientAddr
        ///,S.[ClientCity]
        ///,S.[ClientZipCode]
        ///,S.[ClientState]
        ///,S.ClientPh
        ///,S.QbDocNo
        ///,S.PadId
        ///,S.PhoneId
        ///,S.Eta
        ///,S.StopArrivalTime
        ///,S.StopDepartTime
        ///,S.StopMlgMeterRead
        ///,S.[StopNote]
        ///FROM Pronto.Stop S
        ///JOIN Pronto.Route R ON S.RouteId = R.RootNo
        ///JOIN PRONTO.Customer C ON S.CustomerId = C.ID
        ///JOIN Pronto.Service SV ON SV.ID = S.ServiceId
        ///
        ///WHERE R.RootNo ={0}.
        /// </summary>
        internal static string SelectStop {
            get {
                return ResourceManager.GetString("SelectStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @InsertedRows AS TABLE (Id int);
        ///
        ///UPDATE [Pronto].[Route]
        ///          SET [RouteDate] = @RouteDate
        ///           ,[DriverID] = @DriverID
        ///           ,[TruckId] = @TruckId
        ///           ,[DepatureTime] = @DepatureTime
        ///           ,[ArrivelTime] = @ArrivelTime
        ///           ,[DepartureMilage] = @DepartureMilage
        ///           ,[ArrivelMilage] = @ArrivelMilage
        ///           ,[TotolCod] =@TotolCod
        ///           ,[CodDecrepency] =@CodDecrepency
        ///           ,[HotelInfo] =@HotelInfo
        ///           ,[HotelReceipt] =@Hotel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateRoot {
            get {
                return ResourceManager.GetString("UpdateRoot", resourceCulture);
            }
        }
    }
}
